/*
 * This file was autogenerated by OSQP on Mon May 26 22:45:14 2025
 * 
 * This file contains the prototype for the solver structure needed
 * by OSQP. The actual data is contained inside mpc_mat_workspace.c.
 */

#ifndef MPC_MAT_WORKSPACE_H
#define MPC_MAT_WORKSPACE_H

#include "osqp_api_types.h"

#ifdef __cplusplus
extern "C" {
#endif

  extern OSQPSolver mpc_mat_solver;

#ifdef __cplusplus
}
#endif

#endif /* ifndef MPC_MAT_WORKSPACE_H */
